services:
    enmash_pages.admin.banner:
        class: Enmash\Bundle\PagesBundle\Admin\BannerAdmin
        arguments: [~, Enmash\Bundle\PagesBundle\Entity\Banner, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Содержание, label: Баннеры}

    enmash_pages.admin.article:
        class: Enmash\Bundle\PagesBundle\Admin\ArticleAdmin
        arguments: [~, Enmash\Bundle\PagesBundle\Entity\Article, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Содержание, label: Полезные статьи}

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    enmash_pages.location:
        class: Enmash\Bundle\PagesBundle\EventListener\LocationChangeEventListener
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onRequestMade}

    enmash_pages.store.sortedStores:
        class: Enmash\Bundle\PagesBundle\Component\EnmashServices
        arguments:
            - '@doctrine'
#    enmash_pages.location:
#        class: Enmash\Bundle\PagesBundle\EventListener\LocationChangeEventListener
#        tags:
#            - {name: kernel.event_listener, event: kernel.response, method: onResponseMade}


