enmash_store:
    resource: "@EnmashStoreBundle/Controller/"
    type:     annotation
    prefix:   /

enmash_user_control:
    resource: "@EnmashUserControlBundle/Controller/"
    type:     annotation
    prefix:   /

enmash_pages:
    resource: "@EnmashPagesBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_register:
    resource: '@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml'
    prefix: /register

sonata_user_profile:
    resource: '@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml'
    prefix: /profile

sonata_user_change_password:
    resource: '@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml'
    prefix: /changepassword

sonata_user_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml'
    prefix: /resetting