<?php

namespace Enmash\Bundle\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends EntityRepository {

    public function getOnlyOneTypeOfStores($type) {

        $query = $this
            ->getEntityManager()
            ->getRepository('EnmashStoreBundle:Store')
            ->createQueryBuilder('s')
            ->select('s')
            ->where('s.publish = true');

        switch ($type) {
            case Store::RETAIL_TYPE:
                $query
                    ->andWhere(
                        's.storeType = ' . Store::RETAIL_TYPE . ' OR s.storeType = ' . Store::BOTH_TYPE
                    );
                break;
            case Store::WHOLESALE_TYPE:
                $query
                    ->andWhere(
                        's.storeType = ' . Store::WHOLESALE_TYPE . ' OR s.storeType = ' . Store::BOTH_TYPE
                    );
                break;
            case Store::BOTH_TYPE:
                $query
                    ->andWhere(
                        's.storeType = ' . Store::BOTH_TYPE
                    );
                break;
        }

        return $query->getQuery()->getResult();
    }

}
