<?php

namespace Enmash\Bundle\StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends EntityRepository {

    public function getOnlyOneTypeOfStores($type) {

        $query = $this
            ->getEntityManager()
            ->getRepository('EnmashStoreBundle:Store')
            ->createQueryBuilder('s')
            ->select('s')
            ->where('s.publish = true')
            ->getQuery();

        $stores = $query->getResult();
        if (!$type) {
            return $stores;
        }

        $filteredStores = array();

        if (!is_array($type)) {
            $type = array($type);
        }

        foreach ($stores as $store) {
            foreach ($type as $subType) {
                $add = true;
                /* @var $store \Enmash\Bundle\StoreBundle\Entity\Store */
                if (!in_array($subType, $store->getStoreType())) {
                     $add = false;
                }
            }
            if ($add) {
                $filteredStores[] = $store;
            }
        }

        return $filteredStores;

    }

}
