services:
    enmash_store.admin.product:
        class: Enmash\Bundle\StoreBundle\Admin\ProductAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Product, EnmashStoreBundle:ProductAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product}

    enmash_store.admin.category:
        class: Enmash\Bundle\StoreBundle\Admin\CategoryAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    enmash_store.admin.store:
        class: Enmash\Bundle\StoreBundle\Admin\StoreAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Store, EnmashStoreBundle:StoreAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Store}
