services:
    enmash_store.admin.product:
        class: Enmash\Bundle\StoreBundle\Admin\ProductAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Product, EnmashStoreBundle:ProductAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Product}
        calls:
            - [ setTemplate, [edit, EnmashStoreBundle:Admin:productedit.html.twig] ]

    enmash_store.admin.category:
        class: Enmash\Bundle\StoreBundle\Admin\CategoryAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Category, EnmashStoreBundle:StoreAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Category}

    enmash_store.admin.store:
        class: Enmash\Bundle\StoreBundle\Admin\StoreAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Store, 'PixSortableBehaviorBundle:SortableAdmin']
        tags:
            - {name: sonata.admin, manager_type: orm, group: Магазины, label: Магазины}
        calls:
            - [ setTranslationDomain, [EnmashStoreBundle]]
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]

    enmash_store.admin.store_image:
        class: Enmash\Bundle\StoreBundle\Admin\StoreImageAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\StoreImage, SonataAdminBundle:CRUD, @sonata.media.pool ]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: StoreImage}

    enmash_store.admin.manufacturer:
        class: Enmash\Bundle\StoreBundle\Admin\ManufacturerAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\Manufacturer, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Manufacturer}

    enmash_store.admin.category_parameter:
        class: Enmash\Bundle\StoreBundle\Admin\CategoryParameterAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\CategoryParameter, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: CategoryParameter}

    enmash_store.admin.product_parameter:
        class: Enmash\Bundle\StoreBundle\Admin\ProductParameterAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\ProductParameter, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: ProductParameter}

    enmash_store.admin.store_contact:
        class: Enmash\Bundle\StoreBundle\Admin\StoreContactAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\StoreContact, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: StoreContact}

    enmash_store.catalog_importer:
        class: Enmash\Bundle\StoreBundle\Component\CatalogImporter
        arguments: [@doctrine.orm.entity_manager, @service_container, @kernel]

    enmash_store.admin.special_offer:
        class: Enmash\Bundle\StoreBundle\Admin\SpecialOfferAdmin
        arguments: [~, Enmash\Bundle\StoreBundle\Entity\SpecialOffer, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Содержание, label: Специальные предложения}
